#!/bin/bash
# Patch & auto-generate 'ppl'
# Copyright (c) 2010 GCCSDK Developers

# This is only a temporary script/patch until fix for
# https://www.cs.unipr.it/mantis/view.php?id=102 gets into an official
# release (probably ppl 0.11)

patch -p0 <<_ENDPATCH
--- ../ppl-0.10.2/m4/ac_check_gmp.m4	2009-04-18 07:03:19.000000000 +0200
+++ m4/ac_check_gmp.m4	2010-02-16 21:40:22.000000000 +0100
@@ -54,6 +71,10 @@
 #GMP version 4.1.3 or higher is required
 #endif
 
+#ifndef BITS_PER_MP_LIMB
+#define BITS_PER_MP_LIMB GMP_LIMB_BITS
+#endif
+
 int
 main() {
   std::string header_version;
@@ -80,11 +101,11 @@
     return 1;
   }
 
-  if (sizeof(mp_limb_t)*CHAR_BIT != GMP_LIMB_BITS
-      || GMP_LIMB_BITS != mp_bits_per_limb) {
+  if (sizeof(mp_limb_t)*CHAR_BIT != BITS_PER_MP_LIMB
+      || BITS_PER_MP_LIMB != mp_bits_per_limb) {
     std::cerr
       << "GMP header (gmp.h) and library (ligmp.*) bits-per-limb mismatch:\n"
-      << "header gives " << __GMP_BITS_PER_MP_LIMB << ";\n"
+      << "header gives " << BITS_PER_MP_LIMB << ";\n"
       << "library gives " << mp_bits_per_limb << ".\n"
       << "This probably means you are on a bi-arch system and\n"
       << "you are compiling with the wrong header or linking with\n"
_ENDPATCH

( autoreconf )

