#!/bin/bash -e

cd `dirname $0`

. setup-gccsdk-params

for tool in \
  gcc make libtool automake-1.9 autogen patch makeinfo ; do

  if ! type $tool >/dev/null 2>&1 ; then
    echo "'$tool' couldn't be found.  This needs to be installed for GCCSDK".
    exit 1
  fi
done

function error_handler {
  echo ""
  echo "Looks like the build failed.  You might want to check out the README for what to do now."
  echo ""
  echo "If 'build-cross-output.txt' exists, this will contain a record of the failure.  You can send the end of it to the GCCSDK mailing list for help."
  echo "Once you fix the problem, you can simply run this script again."
  echo ""
  exit 1
}

trap error_handler ERR

make 2>&1 | tee build-cross-output.txt

./install-env

echo "Built and installed GCCSDK cross compiler ok.  Check out the README for examples of how to use the cross compiler or autobuilder"
