#!/bin/bash
# Written by Alan Buckley <alan_baa@hotmail.com>
# Copyright (c) 2008-2012 GCCSDK Developers
#
# Sets the versions of the RISC OS Packaging project
# packaged created
#
# Version numbers are made of upstream version,
# package version followed by text to give idea to
# a user of what it is.
#
# The package version should be updated with each
# release and reset only if the upstream version changes

if [ -z "$GCCSDK_SUPPORTED_GCC_RELEASE" ] ; then
  echo \$GCCSDK_SUPPORTED_GCC_RELEASE is not defined
fi

if [ -z "$GCCSDK_RELEASE_NAME" ] ; then
  echo \$GCCSDK_RELEASE_NAME is not defined
fi

export RPKG_SHAREDLIBS_VERSION=3.0-$GCCSDK_RELEASE_NAME-1

# The C shared libraries includes libunixlib, libgcc
# and libm so use the GCCSDK version, but remember
# to update the the package version if anything
# else changes
export RPKG_SHAREDLIBSC_VERSION=$GCCSDK_SUPPORTED_GCC_RELEASE-$GCCSDK_RELEASE_NAME-1

# The version of SharedLibs-C++ package started to use the .so version
# number which is in retrospect unfortunate.  Hence we now add the
# gcc version number in order to make a difference between same
# libstdc++ versions in different gcc releases.
export RPKG_SHAREDLIBSGPP_VERSION=6.0.8.$GCCSDK_SUPPORTED_GCC_RELEASE-$GCCSDK_RELEASE_NAME-1

# The following two modules, should only be uploaded to the
# packaging site if they area actually changed and in this
# case the version numbers must be changed.
# The versions numbers are the version numbers of the modules

export RPKG_UNIXLIB_VERSION=1.12-1

export RPKG_DRENDERER_VERSION=0.55-1

