#!/bin/bash -e
# Auto-generate libscl
# Copyright (c) 2007-2009 GCCSDK Developers

# In case the installed autoconf version is not 2.59 but
# there is an autoconf2.59 installed instead:
if [ ! -z "`which autoconf2.59`" ] ; then
  export AUTOCONF=autoconf2.59
fi
if [ ! -z "`which autom4te2.59`" ] ; then
  export AUTOM4TE=autom4te2.59
fi

if [ ! -d ./libscl ] ; then
  echo "./libscl is not a directory"
  exit 1
fi

( cd libscl && aclocal-1.9 -I ./ && autoheader && automake-1.9 -a && autoconf )
