#!/bin/bash
# Auto-generate 'gcc' as we've patched it.
# Copyright (c) 2009 GCCSDK Developers

# In case the installed autoconf version is not 2.59 but
# there is an autoconf2.59 installed instead:
if [ ! -z "`which autoconf2.59`" ] ; then
  export AUTOCONF=autoconf2.59
fi
if [ ! -z "`which autom4te2.59`" ] ; then
  export AUTOM4TE=autom4te2.59
fi

( autogen Makefile.def )
( autoconf )
