#!/bin/bash -e
# Auto-generate libunixlib
# Copyright (c) 2007-2009 GCCSDK Developers

# In case the installed autoconf version is not 2.59 but
# there is an autoconf2.59 installed instead:
if [ ! -z "`which autoconf2.59`" ] ; then
  export AUTOCONF=autoconf2.59
fi
if [ ! -z "`which autom4te2.59`" ] ; then
  export AUTOM4TE=autom4te2.59
fi

if [ ! -d ./libunixlib ] ; then
  echo "./libunixlib is not a directory"
  exit 1
fi

# Generate the Makefile.am files:
./libunixlib/gen-auto.pl

# Patch libtool.m4:
( cd libunixlib && cp libtool-org.m4 libtool.m4 && patch -p0 < libtool.m4.p )

# Run the autotools:
( cd libunixlib && aclocal-1.9 -I ./ && autoheader && automake-1.9 -a && autoconf )
