#!/usr/bin/python3

"""
Minimal zip implementation suitable for creating RISC OS zipfiles
"""

import argparse
from contextlib import suppress
import datetime
import os
import shutil
import struct
import zipfile


class Zip:
    def __init__(self, args):
        self._args = args
        self._compression = zipfile.ZIP_STORED

    def run(self):
        if self._args.level > 0:
            self._compression = zipfile.ZIP_DEFLATED

        with zipfile.ZipFile(
            self._args.zipfile,
            "w",
            compression=self._compression,
            compresslevel=self._args.level
        ) as outf:
            for file in self._args.file:
                self._add_item(outf, file)

    @staticmethod
    def _convert_riscos_filetype(zinfo: zipfile.ZipInfo):
        filetype = 0xfff
        if not zinfo.is_dir():
            parts = zinfo.filename.rsplit(",", 1)
            if len(parts) == 2 and len(parts[1]) == 3:
                with suppress(ValueError):
                    filetype = int(parts[1], 16)
                    zinfo.filename = zinfo.filename[:-4]
            elif len(parts) == 1 and "." in parts[0]:
                # No ,xxx and "." in filename: defer to MimeMap
                return

        mtime = int(datetime.datetime(*zinfo.date_time).timestamp())
        tmlo = (mtime & 0x00ffffff) * 100 + 0x00996a00
        tmhi = ((mtime & 0xff000000) >> 24) * 100 + 0x0000336e + (tmlo >> 24)

        loadaddr = 0xfff00000 | (filetype << 8) | ((tmhi >> 8) & 0xff)
        execaddr = (tmlo & 0x00ffffff) | ((tmhi & 0x000000ff) << 24)
        attrs = 0x13  # Private r/w, no public access, unlocked
        zinfo.extra = struct.pack(
            "<HHIIIII", 0x4341, 20, 0x30435241, loadaddr, execaddr, attrs, 0
        )


    def _add_item(self, outf: zipfile.ZipFile, item: str):
        zinfo = zipfile.ZipInfo.from_file(item)
        if not self._args.quiet:
            print(f"Adding {item}")
        if self._args.riscos_filetypes:
            self._convert_riscos_filetype(zinfo)
        if zinfo.is_dir():
            zinfo.compress_size = 0
            zinfo.CRC = 0
            outf.mkdir(zinfo)
            if self._args.recurse:
                for child in os.listdir(item):
                    self._add_item(outf, os.path.join(item, child))
            return

        zinfo.compress_type = self._compression
        if hasattr(zinfo, "compress_level"):
            zinfo.compress_level = self._args.level
        else:
            # Python <3.13
            zinfo._compresslevel = self._args.level
        with open(item, "rb") as src, outf.open(zinfo, "w") as dst:
            shutil.copyfileobj(src, dst, 1024*8)


def main():
    parser = argparse.ArgumentParser(description="RISC OS compatible zip")
    parser.add_argument(
        "-,",
        action="store_true",
        default=False,
        dest="riscos_filetypes",
        help="strip ,xxx from filename and convert to RISCOS filetype encoding",
    )
    parser.add_argument(
        "-0",
        action="store_const",
        const=0,
        dest="level",
        default=0,
        help="store only",
    )
    parser.add_argument(
        "-1",
        action="store_const",
        const=1,
        dest="level",
        help="compress faster",
    )
    parser.add_argument(
        "-9",
        action="store_const",
        const=9,
        dest="level",
        help="compress better",
    )
    parser.add_argument(
        "-r",
        action="store_true",
        default=False,
        dest="recurse",
        help="recurse into directories",
    )
    parser.add_argument(
        "-q",
        action="store_true",
        default=False,
        dest="quiet",
        help="quiet operation",
    )
    parser.add_argument("zipfile")
    parser.add_argument("file", nargs="+")
    args = parser.parse_args()
    Zip(args).run()


if __name__ == "__main__":
    main()
