name: "Build"

on:
  push:
  workflow_dispatch:

jobs:
  cross:
    name: "Build cross compiler (${{ matrix.triplet }})"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        triplet:
          - arm-unknown-riscos
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               autoconf
               autogen
               automake
               bison
               build-essential
               flex
               gperf
               help2man
               libtool
               rename
               subversion
               texinfo

    - name: Create output directory
      run: mkdir -p /opt/riscos-gccsdk/${{ matrix.triplet }}

    # Unspeakable evil: bend the build-world script to our needs
    - name: Create build parameters
      env:
        GCCSDK_ROOT: /opt/riscos-gccsdk/${{ matrix.triplet }}/foo
      run: |
        mkdir /opt/riscos-gccsdk/${{ matrix.triplet }}/foo
        $(pwd)/gcc4/build-world || true
        mv /opt/riscos-gccsdk/${{ matrix.triplet }}/foo/gccsdk-params gcc4/gccsdk-params
        rmdir /opt/riscos-gccsdk/${{ matrix.triplet }}/foo

    - name: Build the cross toolchain
      env:
        MAKEFLAGS: -j
      run: $(pwd)/gcc4/build-world

    - name: Package binaries (with permissions)
      run: tar --owner=root:0 --group=root:0
               -caf riscos-gccsdk-${{ matrix.triplet }}.tar.xz
               -C /
               opt/riscos-gccsdk

    - name: Build the native RISC OS toolchain
      run: make -C gcc4 ronative

    - name: Build kits
      run: |
        $(pwd)/gcc4/create-gcckit -pkg
        $(pwd)/gcc4/create-riscpkg

    # This must be the last step that interacts with the source
    # or install trees, as it deletes things from both during clean
    - name: Package sources
      run: |
        make -C gcc4 -i clean
        git archive -o riscos-gccsdk-${{ matrix.triplet }}-src.tar HEAD
        tar --owner=root:0 --group=root:0 \
            -rf riscos-gccsdk-${{ matrix.triplet }}-src.tar \
            gcc4/gccsdk-params \
            gcc4/srcdir.orig
        xz riscos-gccsdk-${{ matrix.triplet }}-src.tar

    - name: Upload binary artifact
      uses: actions/upload-artifact@v7
      with:
        name: riscos-gccsdk-${{ matrix.triplet }}
        path: riscos-gccsdk-${{ matrix.triplet }}.tar.xz
        archive: false

    - name: Upload source artifact
      uses: actions/upload-artifact@v7
      with:
        name: riscos-gccsdk-${{ matrix.triplet }}-src
        path: riscos-gccsdk-${{ matrix.triplet }}-src.tar.xz
        archive: false

    - name: Upload RISC OS binaries and sources
      uses: actions/upload-artifact@v7
      with:
        name: riscos-gccsdk-${{ matrix.triplet }}-risc_os.zip
        path: |
          gcc4/release-area/kits/*.zip
          gcc4/release-area/kits/*.tar.bz2
          gcc4/release-area/riscpkg/*.zip
